services:

  server-eureka:
    build: ./eureka-server
    container_name: server-eureka
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx192m"
    mem_limit: 512m


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    mem_limit: 384m
    networks: [microservices-network]

  anggota-service:
    build: ./anggota-service
    ports: ["8081:8081"]
    environment:
      JAVA_TOOL_OPTIONS: "-Xms64m -Xmx128m"
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:h2:file:/data/anggota
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://server-eureka:8761/eureka/
    volumes:
      - anggota_data:/data
    mem_limit: 384m
    networks: [microservices-network]

  buku-service:
    build: ./buku-service
    ports: ["8082:8082"]
    environment:
      JAVA_TOOL_OPTIONS: "-Xms64m -Xmx128m"
      SPRING_DATASOURCE_URL: jdbc:h2:file:/data/buku
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://server-eureka:8761/eureka/
    volumes:
      - buku_data:/data
    mem_limit: 384m
    networks: [microservices-network]

  peminjaman-command-service:
    build: ./peminjaman-command-service
    ports: ["8087:8087"]
    environment:
      JAVA_TOOL_OPTIONS: "-Xms64m -Xmx128m"
      SPRING_DATASOURCE_URL: jdbc:h2:file:/data/peminjaman_command
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://server-eureka:8761/eureka/
    volumes:
      - peminjaman_command_data:/data
    mem_limit: 384m
    networks: [microservices-network]

  peminjaman-query-service:
    build: ./peminjaman-query-service
    ports: ["8088:8088"]
    environment:
      JAVA_TOOL_OPTIONS: "-Xms64m -Xmx128m"
      SPRING_DATASOURCE_URL: jdbc:h2:file:/data/peminjaman_query
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://server-eureka:8761/eureka/
    volumes:
      - peminjaman_query_data:/data
    mem_limit: 384m
    networks: [microservices-network]

  pengembalian-service:
    build: ./pengembalian-service
    ports: ["8084:8084"]
    environment:
      JAVA_TOOL_OPTIONS: "-Xms64m -Xmx128m"
      SPRING_DATASOURCE_URL: jdbc:h2:file:/data/pengembalian
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://server-eureka:8761/eureka/
    volumes:
      - pengembalian_data:/data
    mem_limit: 384m
    networks: [microservices-network]

  api-gateway-pustaka:
    build: ./api-gateway-pustaka
    ports: ["9000:9000"]
    environment:
      JAVA_TOOL_OPTIONS: "-Xms64m -Xmx128m"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://server-eureka:8761/eureka/
    mem_limit: 512m
    networks: [microservices-network]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    mem_limit: 1024m
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks: [microservices-network]

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.10
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks: [microservices-network]

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    mem_limit: 512m
    ports: ["5601:5601"]
    networks: [microservices-network]

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 1024m
    networks: [microservices-network]

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks: [microservices-network]

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks: [microservices-network]
    depends_on:
      - prometheus

volumes:
  anggota_data:
  buku_data:
  peminjaman_command_data:
  peminjaman_query_data:
  pengembalian_data:
  elasticsearch_data:
  jenkins_home:

networks:
  microservices-network:
    driver: bridge
